# version of Kubernetes API
apiVersion: v1
# define a Secret object
kind: Secret
# metadata of the Secret object
metadata: 
  # name of the Secret object
  name: mongodb-secret 
# stringData of the Secret object
stringData: 
  # sets the stringData for the Secret object
  MONGO_ROOT_USERNAME: admin 
# data of the Secret object
data: 
  # sets the data "MONGO_ROOT_PASSWORD" to the value "c3VwZXJzZWNyZXRwYXNzd29yZA==" (base64 encoded string of "supersecretpassword")
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== 