# use CircleCI 2.1
version: 2.1 
# define a job to be executed
jobs: 
  # define the job name as "lint-dockerfile"
  lint-dockerfile: 
    # run the job in a Docker container
    docker: 
      - image: cimg/base:stable # use the cimg/base:stable Docker image
    # define the job steps
    steps: 
      - checkout # checkout the code from the Git repository
      - setup_remote_docker # setup the Docker daemon
      - run: # run the job steps
          name: Install Hadolint
          command: docker pull ghcr.io/hadolint/hadolint
      - run: # run the job steps
          name: Run Hadolint
          command: docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile

  # define the job name as "build-app-karsajobs-ui"
  build-app-karsajobs-ui: 
    # run the job in a Docker container
    docker: 
      - image: cimg/base:stable # use the cimg/base:stable Docker image
    # define the job steps
    steps: 
      - checkout # checkout the code from the Git repository
      - setup_remote_docker # setup the Docker daemon
      - run:
          name: Build Image
          command: docker build -t septriputraw/karsajobs-ui:latest .
      - run:
          name: Change Tag
          command: docker tag septriputraw/karsajobs-ui:latest ghcr.io/septriputraw/karsajobs-ui:latest
      - run:
          name: Login to Github Packages
          command: echo $GITHUB_TOKEN | docker login ghcr.io -u septriputraw --password-stdin
      - run:
          name: Push to Github Packages
          command: docker push ghcr.io/septriputraw/karsajobs-ui:latest

# define a workflow
workflows: 
  # define the workflow name as "karsajobs-ui-workflow"
  karsajobs-ui-workflow: 
    # define the workflow jobs
    jobs: 
      - lint-dockerfile # execute the "lint-dockerfile" job
      - build-app-karsajobs-ui: # define the job name as "build-app-karsajobs-ui" and wait for the "lint-dockerfile" job to finish
          requires:
            - lint-dockerfile